linters:
  ClassesBeforeIds:
    enabled: true
    EnforcedStyle: 'id'

  LineLength:
    enabled: false

  ViewLength:
    enabled: false

  RuboCop:
    ignored_cops:
      - Style/IfUnlessModifier
