name: Styles
on: [push]
jobs:
  styles:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Bundle check
      run: |
        bundle check
    - name: YAML syntax
      run: |
        find . -path ./node_modules -prune -o -type f \( -name '*.yml' -o -name '*.yaml' \) -print \
          | xargs -I{} ruby -ryaml -e "YAML.unsafe_load_file('{}')"
    - name: RuboCop
      run: |
        bundle exec rubocop
    - name: Prettier
      run: |
        bin/bundle exec rbprettier --check .
    - name: haml-lint
      run: |
        bundle exec haml-lint --exclude 'lib/**/*.haml'
    - name: scss-lint
      run: |
        bundle exec scss-lint --format JSON
    - name: Setup and run brakeman
      run: |
        gem install brakeman
        brakeman --exit-on-warn --quiet -f plain --safe-methods sanitize
